export const metadata = {
    title: "Programacao",
    description: "Generated by create next app",
  };
  

export default function ProgramacaoLayout({ children }) {
    return (
      <>
      {children}
      </>
    )
  }