import "./globals.css";
import "@/app/styles/all.css";
import Footer from "@/components/footer";

import Header from "@/components/header";


export const metadata = {
  title: "Satsconf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
