export const metadata = {
    title: "Palestrantes",
    description: "Generated by create next app",
  };
  

export default function PalestrantesLayout({ children }) {
    return (
      <>
      {children}
      </>
    )
  }